import Head from "next/head";
import Card from "../components/Card";
import Button from "../util/Button";
import { IoChevronForwardOutline } from "react-icons/io5";
import { useRouter } from "next/router";
import cryptoIcon from "../asset/cryptoIcon.png";
import Image from "next/image";
import WalletModal from "../components/WalletModal";
import { TransactionContext } from "../context/TransactionContext";
import { useContext, useEffect } from "react";
import LatestFeed from "../components/LatestFeed";

export default function Home() {
  const router = useRouter();
  const { connectWallet, currentAccount } = useContext(TransactionContext);

  useEffect(() => {
    console.log("update...");
  }, [currentAccount]);

  return (
    <div className="flex grow h-full">
      <Head>
        <title>Exaverse</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./icon.ico" />
      </Head>
      <main className="flex flex-col w-full gap-y-4 ">
        <div className=" min-w-[200px] sm:w-64 flex gap-x-2 lg:flex-col lg:gap-y-4">
          <Card>
            <div className="flex flex-col items-center gap-y-4 px-4 py-2 sm:gap-y-4 sm:px-4 sm:py-1 sm:px-1 w-96 ">
              <h1 className="text-2xl font-semibold sm:text-xl">
                Convert to any Crypto Currency
              </h1>
              <Image src={cryptoIcon} alt="crpto icon" />
              <div className="w-full flex flex-col items-stretch static">
                {currentAccount ? (
                  <button
                    className="w-full flex justify-center items-center gap-x-2 bg-primary-color rounded p-2"
                    onClick={() => router.push("/swap")}
                  >
                      <p className="text-lg sm:text-sm">Convert Now</p>
                      <IoChevronForwardOutline className="text-xl" />
                  </button>
                ) : (
                  <WalletModal />
                )}
              </div>
            </div>
          </Card>
          <Card>
            <div className="flex flex-col gap-y-2">
              <h1 className="text-2xl font-bold">
                Transaction amount to any Account
              </h1>
              <button
                className="rounded p-2 bg-dark-light hover:bg-primary-color"
                onClick={() => router.push("/transaction")}
              >
                Send
              </button>
            </div>
          </Card>
        </div>
        <LatestFeed />
      </main>
    </div>
  );
}
