import Card from "../components/Card";
import Head from "next/head";
import { MdSwapVert } from "react-icons/md";
import Button from "../util/Button";

const Swap = () => {
  return (
    <div className="flex flex-1 items-center justify-center flex-col text-white">
      <Head>
        <title>Blockchain App - Coin Swap</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="bg-primary-color px-4 py-2 rounded mb-10 text-2xl font-semibold tracking-wide">
        <p>Swap Your Crypto Here</p>
      </div>
      <Card>
        <div className="flex flex-col items-center gap-y-4">
          <p className="mb-4">Swap</p>
          <div className="bg-dark-primary rounded px-4 py-2">
            <input className="bg-dark-primary text-xl py-3 px-4 focus:outline-none" />
            <select className="bg-dark-light rounded p-2">
              <option className="hover:bg-primary-color rounded p-4">
                Testing
              </option>
              {/* ADD Remove this select block and add custom menu where user can search crypto */}
            </select>
          </div>
          <div className="p-2 text-xl bg-primary-color rounded">
            <MdSwapVert />
          </div>
          <div className="bg-dark-primary rounded px-4 py-2">
            <input className="bg-dark-primary text-xl py-3 px-4 focus:outline-none" />
            <select className="bg-dark-light rounded p-2">
              <option>Testing</option>
            </select>
          </div>
          <Button>
            <p>Convert Now</p>
          </Button>
        </div>
      </Card>
    </div>
  );
};

export default Swap;
